### ISSUE TITLE
Power-up drops

### ISSUE THREAD

**Issue by amorata604** [Infiland/AsteroidsFeedback#24] opened 2024-08-14 11:44 UTC
I`ve been trying to beat 4x4 sectors with Super Skip. Well, at least when you can beat at first blue, purple and brown asteroids, equiping clone, it could be beatable. Although, the late game could be more interesting if asteroids drop power-ups when breaking. I`ve been thinking of some ideas:

- Healing drop: no much mystery, heals the spaceship when damaged.
- Shield drop: have a time limit protection against shoots and hitting asteroids.
- Pulse drop: acting as the Pulse gun with a time limit (it would be more fair when player doesn't equip Pulse gun).
- Explosive drop: acting as Nuke ability, destroys the entire area where the drop is located (without affecting the player).
- Special recruitment drop: knowing that Recruitments at late game struggle because of hitting huge asteroids, this recruitments can have more protection and special habilities to deal with this problem during a limit of time.
- Upgraded weapons drop: shooting weapons can have extra penetration, extra damage or fast fire rate during a limit of time.
- 2x gold drop: collect the double of gold during a limit of time.
- Hard body drop: spaceship gets inmmune to asteroids damage and deals body damage during a limit of time.

Although this power-ups can be gotten easily with small asteroids, this wouldn't be fair. There should be a small chance to get them from large and huge asteroids.

**Comment by Infiland** [comment] 2024-08-14 17:24
Yes, this is planned to be added as an utility called "Space Gifts". It would be dropped from UFOs or larger asteroids in limited quanities (each level increases max quantity that can spawn) which gives temporary effects on the sector.

Like you said, these drops are best used for late game, as the player with those gifts gets progressively more powerful, which is also intended. Some of the ideas that you posted are some that I havent considered myself so thanks for putting that out there!

Not sure when I'll add this but I'm thinking somewhere around 1.2.0

**Comment by Infiland** [comment] 2024-12-13 10:27
Confirmed in 1.2.5, will close this issue when the update is released

**Comment by Infiland** [comment] 2024-12-16 20:40
Added in 1.2.5

**Closed as completed by Infiland** 2024-12-16 20:40 UTC
Labels: feature
